import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Full Stack Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}



/*
Prisma is the ORM tool -> which is Object Relational Mapping 
It makes easier to work with any type of the databases whether SQL or NoSQL
It is mainly used insides the backend inside node.js application 
in which it makes easier to query the database , to post something to the database,

It just create a schema and schema is map to any database
and then prisma gives us client and client can have all of the query and inserion to the database and so many things

*/